name = "Economy Pack"
author = "Grant"
version = "1.0.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ebc225b04d7318d08e2bb75816998227f3eda2d18cf84a56609ae5b0d653b05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
