name = "Economy Pack"
author = "Grant"
version = "1.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199a57d5d362f55f133445c22372172f1fc2d7eda8e41e85eb3e05d2e72eebdf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
