name = "Economy Pack"
author = "Grant"
version = "1.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6110b7eb651ac7ff3024cdaf3e366e192a8efd3249ba49cad0615f1976e1ae1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
