"""
Sieve balance: scales Ex Deorum sieve drop chances for the goods that made sieving dominate the economy.

Run:  python3 tools/build_sieve.py  ->  kubejs/server_scripts/economy_sieve.js

The original odds are snapshotted once into tools/sieve_base_odds.json (from the KubeJS export, before any change),
so rerunning never compounds the scaling and tools/pacing_sim.py can model the same numbers.
Delete the snapshot only if a mod update changes the base recipes, and re-export first with the script disabled.
"""
import glob
import json
import os

PACK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORT = os.path.expanduser('~/Library/Application Support/PrismLauncher/instances/Economy Test/minecraft/local/kubejs/export')
SNAPSHOT = os.path.join(os.path.dirname(__file__), 'sieve_base_odds.json')

# Multiplier on the drop chance of each good, for every mesh and input block (gravel, crushed deepslate) on both
# the normal and compressed sieves. Grant, 2026-10-05: halve ore, cut gems, gates x2 (see PACING-REPORT.md).
SCALE = {
    'exdeorum:iron_ore_chunk': 0.5,
    'exdeorum:gold_ore_chunk': 0.5,
    'exdeorum:copper_ore_chunk': 0.5,
    'exdeorum:zinc_ore_chunk': 0.5,
    'minecraft:lapis_lazuli': 0.6,
    'minecraft:amethyst_shard': 0.6,
}


def snapshot():
    """recipe id -> original recipe json, for every sieve recipe that drops a scaled good."""
    if os.path.exists(SNAPSHOT):
        return json.load(open(SNAPSHOT))
    base = os.path.join(EXPORT, 'recipes')
    out = {}
    for kind in ('sieve', 'compressed_sieve'):
        for f in glob.glob(os.path.join(base, 'exdeorum', kind, '**', '*.json'), recursive=True):
            d = json.load(open(f))
            if d.get('result', {}).get('id') in SCALE:
                rid = 'exdeorum:' + os.path.relpath(f, os.path.join(base, 'exdeorum'))[:-5].replace(os.sep, '/')
                out[rid] = d
    json.dump(out, open(SNAPSHOT, 'w'), indent=1, sort_keys=True)
    return out


def scaled(recipe):
    d = json.loads(json.dumps(recipe))
    a = d['result_amount']
    a['p'] = round(a['p'] * SCALE[d['result']['id']], 4)
    return d


def base_odds(block, mesh, kind='sieve'):
    """Expected count per operation of every scaled good, after scaling (for the pacing simulator)."""
    out = {}
    for rid, d in snapshot().items():
        if rid.startswith(f'exdeorum:{kind}/{block}/{mesh}/'):
            a = scaled(d)['result_amount']
            out[d['result']['id']] = out.get(d['result']['id'], 0) + a['n'] * a['p'] * d['result'].get('count', 1)
    return out


def main():
    recipes = snapshot()
    lines = ['// Economy Pack sieve balance. Generated by tools/build_sieve.py; edit that file instead.',
             '// Replaces Ex Deorum sieve recipes with lower drop chances for ores and gems.', '',
             'const SIEVE_NERF = [']
    for rid in sorted(recipes):
        lines.append(f'  [{json.dumps(rid)}, {json.dumps(scaled(recipes[rid]), sort_keys=True)}],')
    lines += [']', '',
              'ServerEvents.recipes(event => {',
              '  SIEVE_NERF.forEach(([id, json]) => {',
              '    event.remove({ id: id })',
              "    event.custom(json).id(id.replace('exdeorum:', 'economy_core:balanced_'))",
              '  })',
              '})', '']
    js = os.path.join(PACK, 'kubejs', 'server_scripts', 'economy_sieve.js')
    open(js, 'w').write('\n'.join(lines))
    print(f'{len(recipes)} sieve recipes rescaled -> {js}')


if __name__ == '__main__':
    main()
