"""
Sieve balance: scales Ex Deorum sieve drop chances for the goods that made sieving dominate the economy.

Run:  python3 tools/build_sieve.py  ->  kubejs/server_scripts/economy_sieve.js

The original odds are snapshotted once into tools/sieve_base_odds.json (from the KubeJS export, before any change),
so rerunning never compounds the scaling and tools/pacing_sim.py can model the same numbers.
Delete the snapshot only if a mod update changes the base recipes, and re-export first with the script disabled.
"""
import glob
import json
import os

PACK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402
EXPORT = paths.export_dir()
SNAPSHOT = os.path.join(os.path.dirname(__file__), 'sieve_base_odds.json')
# Pebble drops removed from every sieve except dirt (Grant, 2026-10-05: they clog the output). Dirt keeps its pebbles:
# they're the only cobblestone before the first cobble generator. Snapshotted like the odds so a later export (which
# won't contain the removed recipes) can't shrink the list.
PEBBLE_SNAPSHOT = os.path.join(os.path.dirname(__file__), 'sieve_pebbles.json')

# Multiplier on the drop chance of each good, for every mesh and input block (gravel, crushed deepslate) on both
# the normal and compressed sieves. Grant, 2026-10-05: first x0.5/x0.6 with gates x2, then steeper (x0.35/x0.45)
# alongside the Power Exchange so sieves help the early tiers without driving the late game (see PACING-REPORT.md).
SCALE = {
    'exdeorum:iron_ore_chunk': 0.35,
    'exdeorum:gold_ore_chunk': 0.35,
    'exdeorum:copper_ore_chunk': 0.35,
    'exdeorum:zinc_ore_chunk': 0.35,
    'minecraft:lapis_lazuli': 0.45,
    'minecraft:amethyst_shard': 0.45,
}


def snapshot():
    """recipe id -> original recipe json, for every sieve recipe that drops a scaled good."""
    if os.path.exists(SNAPSHOT):
        return json.load(open(SNAPSHOT))
    base = os.path.join(EXPORT, 'recipes')
    out = {}
    for kind in ('sieve', 'compressed_sieve'):
        for f in glob.glob(os.path.join(base, 'exdeorum', kind, '**', '*.json'), recursive=True):
            d = json.load(open(f))
            if d.get('result', {}).get('id') in SCALE:
                rid = 'exdeorum:' + os.path.relpath(f, os.path.join(base, 'exdeorum'))[:-5].replace(os.sep, '/')
                out[rid] = d
    json.dump(out, open(SNAPSHOT, 'w'), indent=1, sort_keys=True)
    return out


def pebble_recipes():
    """Recipe ids of every sieve pebble drop, except from dirt."""
    if os.path.exists(PEBBLE_SNAPSHOT):
        return json.load(open(PEBBLE_SNAPSHOT))
    base = os.path.join(EXPORT, 'recipes', 'exdeorum')
    out = []
    for kind in ('sieve', 'compressed_sieve'):
        for f in glob.glob(os.path.join(base, kind, '**', '*.json'), recursive=True):
            rid = 'exdeorum:' + os.path.relpath(f, base)[:-5].replace(os.sep, '/')
            d = json.load(open(f))
            if d.get('result', {}).get('id', '').endswith('_pebble') and '/dirt/' not in rid:
                out.append(rid)
    out.sort()
    json.dump(out, open(PEBBLE_SNAPSHOT, 'w'), indent=1)
    return out


def scaled(recipe):
    d = json.loads(json.dumps(recipe))
    a = d['result_amount']
    a['p'] = round(a['p'] * SCALE[d['result']['id']], 4)
    return d


def base_odds(block, mesh, kind='sieve'):
    """Expected count per operation of every scaled good, after scaling (for the pacing simulator)."""
    out = {}
    for rid, d in snapshot().items():
        if rid.startswith(f'exdeorum:{kind}/{block}/{mesh}/'):
            a = scaled(d)['result_amount']
            out[d['result']['id']] = out.get(d['result']['id'], 0) + a['n'] * a['p'] * d['result'].get('count', 1)
    return out


def main():
    recipes = snapshot()
    lines = ['// Economy Pack sieve balance. Generated by tools/build_sieve.py; edit that file instead.',
             '// Replaces Ex Deorum sieve recipes with lower drop chances for ores and gems.', '',
             'const SIEVE_NERF = [']
    for rid in sorted(recipes):
        lines.append(f'  [{json.dumps(rid)}, {json.dumps(scaled(recipes[rid]), sort_keys=True)}],')
    pebbles = pebble_recipes()
    lines += [']', '', '// Pebble drops removed from every sieve except dirt.', 'const NO_PEBBLES = [']
    lines += [f'  {json.dumps(rid)},' for rid in pebbles]
    lines += [']', '',
              'ServerEvents.recipes(event => {',
              '  SIEVE_NERF.forEach(([id, json]) => {',
              '    event.remove({ id: id })',
              "    event.custom(json).id(id.replace('exdeorum:', 'economy_core:balanced_'))",
              '  })',
              '  NO_PEBBLES.forEach(id => event.remove({ id: id }))',
              '})', '']
    js = os.path.join(PACK, 'kubejs', 'server_scripts', 'economy_sieve.js')
    open(js, 'w').write('\n'.join(lines))
    print(f'{len(recipes)} sieve recipes rescaled, {len(pebbles)} pebble drops removed -> {js}')


if __name__ == '__main__':
    main()
